spring.application.name=portfolio
# Server
server.port=8080

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chirag2001daorha@gmail.com
spring.mail.password=ifal byql rvlf evob
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Your email where you want to receive messages
portfolio.receiver-email=chirag2001daorha@gmail.com